#Theme Name: Handsomely
#CMS - Jekyll
#Developer- Deenesh Chowdhary
#http://deeneshchowdhary.com
title: Twitter usage study
site-description: "Extension of the paper Testing Propositions Derived from Twitter Studies: Generalization and Replication in Computational Social Science from Hai Liang and King-wa Fu"
email: your-email@domain.com
description: "small description about you will take you long"
baseurl: "https://mathildehermet.github.io/twitter_research_paper_extension" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email_username: mathilde.hermet@epfl.ch #Your email address
twitter_username: HermetMathilde
github_username: epfl-ada/ada-2020-project-milestone-p3-p3_kali #Github Username goes here
your_name: Kali #Your Name for About
about_yourself: "We are Mathilde Hermet, Quentin Müller and Aleandro Eccel, 3 students at the EPFL engineering school.
We are a team of 3 applied data analysts willing to see if we can find a model based on user datas that predicts the future usage." # Brief description about yourself
copyright_name: Kali #Copyright
# Build settings
markdown: kramdown
paginate: 3 #Total Number of Post in each Page
gems: [jekyll-paginate, jekyll-feed]
exclude:
  - Gemfile
  - Gemfile.lock
